name: Maven Compile on Push

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: ['17']
        name: Java (Temurin) ${{ matrix.java }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up Eclipse Temurin
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
                  java-package: jdk
                  cache: 'maven'
            - name: Compile with Maven
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: mvn -B clean package